### ISSUE TITLE
"TypeError: Cannot read property of 'paused' of undefined"

### ISSUE THREAD

**Issue by AmazingArcher23** [nexu-dev/discord.js-music#4]
![archer12306_february_2017_cmd](https://cloud.githubusercontent.com/assets/18449883/23333193/5e7fd702-fb55-11e6-96bc-75f8eb66bf94.png)
when trying to queue/pause/resume/skip

**Comment by nexu-dev** [comment]
This plugin is for v11, not Prism.  
I'll work on an update soon.
